# Posenet variation to be used for pose estimation
backbone: resnet

# Classification model
model: LSTM


classes:
  - walk
  - stand
  - left
  - right

#Dimension of the video output
output_video_dim:
  - 640
  - 480


# Duration in seconds of each turn
time_rotation: 0.5

# Minimum time interval for an action to be repeated
default_limit: 0.5

# Minimum Classifier output for action != stand
threshold_nn: 0

# Posenet model stride
posenet_stride: 16

# Show skeleton in the output shown
show_skeleton: True


paths:
  posenet: False
  LSTM: False
  #If LSTM is not used, these paths are used
  PCA: False
  NN: False
  SCALER: False

driver_path: C:\some\where\geckodriver.exe